export const GET_LIST_BANNER_REQUEST = 'GET_LIST_BANNER_REQUEST';
export const GET_LIST_BANNER_SUCCESS = 'GET_LIST_BANNER_SUCCESS';
export const GET_LIST_BANNER_FAILED = 'GET_LIST_BANNER_FAILED';

export const GET_CHOOSE_BANNER_REQUEST = 'GET_CHOOSE_BANNER_REQUEST';
export const GET_CHOOSE_BANNER_SUCCESS = 'GET_CHOOSE_BANNER_SUCCESS';
export const GET_CHOOSE_BANNER_FAILED = 'GET_CHOOSE_BANNER_FAILED';
