export const ADD_ONE_PRODUCT_TO_CART_REQUEST =
  'ADD_ONE_PRODUCT_TO_CART_REQUEST';
export const ADD_ONE_PRODUCT_TO_CART_SUCCESS =
  'ADD_ONE_PRODUCT_TO_CART_SUCCESS';
export const ADD_ONE_PRODUCT_TO_CART_FAILED = 'ADD_ONE_PRODUCT_TO_CART_FAILED';
///////////////////////////////////////////////////////////////////////////////////
export const ADD_PRODUCTS_TO_CART_REQUEST = 'ADD_PRODUCTS_TO_CART_REQUEST';
export const ADD_PRODUCTS_TO_CART_SUCCESS = 'ADD_PRODUCTS_TO_CART_SUCCESS';
export const ADD_PRODUCTS_TO_CART_FAILED = 'ADD_PRODUCTS_TO_CART_FAILED';
