export const GET_LIST_LOCATION_REQUEST = 'GET_LIST_LOCATION_REQUEST';
export const GET_LIST_LOCATION_SUCCESS = 'GET_LIST_LOCATION_SUCCESS';
export const GET_LIST_LOCATION_FAILED = 'GET_LIST_LOCATION_FAILED';

export const GET_CHOOSE_LOCATION_REQUEST = 'GET_CHOOSE_LOCATION_REQUEST';
export const GET_CHOOSE_LOCATION_SUCCESS = 'GET_CHOOSE_LOCATION_SUCCESS';
export const GET_CHOOSE_LOCATION_FAILED = 'GET_CHOOSE_LOCATION_FAILED';
