export const GET_LIST_LOCATION_REQUEST = 'GET_LIST_LOCATION_REQUEST';
export const GET_LIST_LOCATION_SUCCESS = 'GET_LIST_LOCATION_SUCCESS';
export const GET_LIST_LOCATION_FAILED = 'GET_LIST_LOCATION_FAILED';
//?????? có cần get list hay ko ??????
export const GET_CHOOSE_LOCATION_REQUEST = 'GET_CHOOSE_LOCATION_REQUEST';
export const GET_CHOOSE_LOCATION_SUCCESS = 'GET_CHOOSE_LOCATION_SUCCESS';
export const GET_CHOOSE_LOCATION_FAILED = 'GET_CHOOSE_LOCATION_FAILED';

export const GET_CHANGE_ADDRESS_REQUEST = 'GET_CHANGE_ADDRESS_REQUEST';
export const GET_CHANGE_ADDRESS_SUCCESS = 'GET_CHANGE_ADDRESS_SUCCESS';
export const GET_CHANGE_ADDRESS_FAILED = 'GET_CHANGE_ADDRESS_FAILED';

export const GET_DELETE_ADDRESS_REQUEST = 'GET_DELETE_ADDRESS_REQUEST';
export const GET_DELETE_ADDRESS_SUCCESS = 'GET_DELETE_ADDRESS_SUCCESS';
export const GET_DELETE_ADDRESS_FAILED = 'GET_DELETE_ADDRESS_FAILED';

export const GET_ADD_ONE_ADDRESS_REQUEST = 'GET_ADD_ONE_ADDRESS_REQUEST';
export const GET_ADD_ONE_ADDRESS_SUCCESS = 'GET_ADD_ONE_ADDRESS_SUCCESS';
export const GET_ADD_ONE_ADDRESS_FAILED = 'GET_ADD_ONE_ADDRESS_FAILED';
