export const POST_DEVICE_TOKEN_REQUEST = 'POST_DEVICE_TOKEN_REQUEST';
export const POST_DEVICE_TOKEN_SUCCESS = 'POST_DEVICE_TOKEN_SUCCESS';
export const POST_DEVICE_TOKEN_FAILED = 'POST_DEVICE_TOKEN_FAILED';

export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAILED = 'GET_NOTIFICATION_FAILED';