
export const GET_CHANGE_LOADING_REQUEST = 'GET_CHANGE_LOADING_REQUEST';
export const GET_CHANGE_LOADING_SUCCESS = 'GET_CHANGE_LOADING_SUCCESS';
export const GET_CHANGE_LOADING_FAILED = 'GET_CHANGE_LOADING_FAILED';
