export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_SUCCESS';
export const GET_ALL_PRODUCTS_FAILED = 'GET_ALL_FAILED';

export const GET_ALL_PRODUCTS_BY_TYPE_REQUEST =
  'GET_ALL_PRODUCTS_BY_TYPE_REQUEST';
export const GET_ALL_PRODUCTS_BY_TYPE_SUCCESS =
  'GET_ALL_PRODUCTS_BY_TYPE_SUCCESS';
export const GET_ALL_PRODUCTS_BY_TYPE_FAILED =
  'GET_ALL_PRODUCTS_BY_TYPE_FAILED';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';

export const GET_ALL_CATEGORIES_BY_TYPE_REQUEST =
  'GET_ALL_CATEGORIES_BY_TYPE_REQUEST';
export const GET_ALL_CATEGORIES_BY_TYPE_SUCCESS =
  'GET_ALL_CATEGORIES_BY_TYPE_SUCCESS';
export const GET_ALL_CATEGORIES_BY_TYPE_FAILED =
  'GET_ALL_CATEGORIES_BY_TYPE_FAILED';

export const GET_ALL_FAVORITE_PRODUCT_REQUEST =
  'GET_ALL_FAVORITE_PRODUCT_REQUEST';
export const GET_ALL_FAVORITE_PRODUCT_SUCCESS =
  'GET_ALL_FAVORITE_PRODUCT_SUCCESS';
export const GET_ALL_FAVORITE_PRODUCT_FAILED =
  'GET_ALL_FAVORITE_PRODUCT_FAILED';
