export const GET_LIST_GEAR_REQUEST = 'GET_LIST_GEAR_REQUEST';
export const GET_LIST_GEAR_SUCCESS = 'GET_LIST_GEAR_SUCCESS';
export const GET_LIST_GEAR_FAILED = 'GET_LIST_GEAR_FAILED';

export const GET_CHOOSE_GEAR_REQUEST = 'GET_CHOOSE_GEAR_REQUEST';
export const GET_CHOOSE_GEAR_SUCCESS = 'GET_CHOOSE_GEAR_SUCCESS';
export const GET_CHOOSE_GEAR_FAILED = 'GET_CHOOSE_GEAR_FAILED';
