export const GET_LIST_CATEGORIES_REQUEST = 'GET_LIST_CATEGORIES_REQUEST';
export const GET_LIST_CATEGORIES_SUCCESS = 'GET_LIST_CATEGORIES_SUCCESS';
export const GET_LIST_CATEGORIES_FAILED = 'GET_LIST_CATEGORIES_FAILED';
